Laba6
test4ment/Spacewar pull request #23
Opened 2024-02-07 11:53 UTC by test4ment

2024-03-01 04:05 UTC, zaryanezrya requested changes

2024-03-01 04:05 UTC, zaryanezrya commented on Spacewar/Commands.cs
> +public class SoftStopServer : ICommand
action?

2024-03-01 04:05 UTC, zaryanezrya commented on Spacewar.tests/Features/server.feature
Check Exception

2024-03-01 04:05 UTC, zaryanezrya commented on Spacewar.tests/Tests/ServerTests.cs
> +    public static void WaitFor(int seconds)
не вызывается

2024-03-01 04:05 UTC, zaryanezrya commented on Spacewar.tests/Tests/ServerTests.cs
> +        Thread.Sleep(150);
В тестах Thread.Sleep не используется

2024-03-15 04:45 UTC, test4ment commented on .gitignore
remove from pr

2024-03-15 04:50 UTC, test4ment commented on Spacewar/DecisionTree.cs
remove from pr

2024-03-15 04:59 UTC, zaryanezrya requested changes

2024-03-15 04:59 UTC, zaryanezrya commented on Spacewar/DecisionTree.cs
--

2024-03-15 04:59 UTC, zaryanezrya commented on Spacewar/Server.cs
del GetHashCode()

2024-03-15 06:58 UTC, test4ment commented
Исправил ветку после force-push'а

2024-05-24 04:47 UTC, zaryanezrya approved these changes

2024-05-27 20:31 UTC, closed without merging